### ISSUE TITLE
Creating AP to bring up captive portal and access mesh in client-side application

### ISSUE THREAD

**Issue by STUDIOCLOUD001** [JoshWeiner/offline-mesh-network#1]
Hey Josh, 

Recently came across your project and read the documentation on [Medium](https://medium.com/codex/untangling-the-mesh-an-exploration-of-offline-network-engineering-9269df3f6a07) - solid work!! Decided to try it out and was able to successfully build and upload the project to three generic ESP8266 modules (using PlatformIO / VSC) which then formed a mesh.  

Now, I just need to configure a fourth ESP8266 module as an Access Point (AP). I like the idea about a captive portal opening up when a user connects to the AP instead of having to type out an ip each time, but I’ve not been able to edit main.cpp in src to create the AP. My experience with PainlessMesh and C++ in general is limited, but if you had a couple of minutes I would be super happy for advice. 

Do I just activate the hidden code after your comment “BELOW: Working single node serving web pages” (see the attached screenshot)? And if I do this how would I define the identifier “webServer”? 
<img width="1440" alt="Hidden" src="https://github.com/JoshWeiner/offline-mesh-network/assets/152998827/367115a3-1809-406c-9b43-a44797fd5489">

Best,
M

**Comment by JoshWeiner** [comment]
Hi M,

The functions to set up an ESP8266 chip as an access point have already been written in main.cpp. All you have to do is uncomment line 214, then simply rebuild and upload the project to all ESP8266 chips which you want to be access points.

Your setup method should look as follows:
```
// On node startup
void setup() {
  Serial.begin(115200);
  
  StartFilesystem();
  StartMesh();
  StartWiFi();
  ConnectToServer();
  ConnectToWebSocket();
  StartMDNS();
}
```

Also be sure to change any SSID, prefix, and passwords to your liking & so that your network is more secure! Most importantly in line 14:
`#define MESH_PASSWORD "joshisgreat"`

Thank you for following the project and for the question! Glad you've been able to use this relatively painlessly.

- Josh
